version: '3.1'
services:
    php-cli:
        image: dockercraft/php:7.2
        container_name: pi-worker-cli
        entrypoint:
            - php
        command: "-v"
        working_dir: "/var/www"
        volumes:
            - .:/var/www

    artisan:
        image: dockercraft/php:7.2
        container_name: pi-worker-artisan
        entrypoint:
            - php
            - artisan
        command: "help"
        working_dir: "/var/www"
        networks:
          devenv:
            ipv4_address: 192.168.33.57
        volumes:
            - .:/var/www
        
    composer:
        image: dockercraft/composer
        container_name: pi-worker-composer
        entrypoint:
            - composer
        command: "-v"
        working_dir: "/var/www"
        volumes:
            - .:/var/www

    php-server:
        image: dockercraft/php:7.2
        container_name: pi-worker-server
        entrypoint:
            - php
        command: "-S 0.0.0.0:8009 -t /var/www/public"
        working_dir: "/var/www"
        networks:
          devenv:
            ipv4_address: 192.168.33.72
        volumes:
            - .:/var/www
        ports:
            - 8009:8009

    queue:
        image: dockercraft/beanstalkd:1.10
        container_name: pi-worker-queue-server
        networks:
          devenv:
            ipv4_address: 192.168.33.110
        ports: 
            - 11300:11300

    worker:
        restart: always
        image: dockercraft/php:7.2
        depends_on:
            - queue
            - php-server
        container_name: pi-worker-queue-worker
        entrypoint:
            - php
            - artisan
        command: "queue:work --queue=high,default --sleep=1 --tries=3 --daemon"
        working_dir: "/var/www"
        networks:
          devenv:
            ipv4_address: 192.168.33.172
        volumes:
            - .:/var/www
    mailhog:
        image: mailhog/mailhog:latest
        container_name: pi-worker-mailhog
        networks:
          devenv:
            ipv4_address: 192.168.33.25
        ports:
          - "8025:8025"

    nginx-html:
        image: nginx:1.15.7-alpine
        container_name: pi-worker-nginx-html
        volumes:
        - ./public:/var/www/html:rw
        - ./provision/nginx/html.conf:/etc/nginx/conf.d/mysite.conf:ro
        restart: on-failure
        networks:
          devenv:
            ipv4_address: 192.168.33.15
        ports:
          - "8115:8115"
        environment:
          - PUID="1000"
          - PGID="1000"
          - TZ="Australia/Melbourne"
          - NGINX_HOST=local.test
          - NGINX_PORT=8115

networks:
  devenv:
    ipam:
      config:
        - subnet: 192.168.33.0/24


